# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Mensagens.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'Mensagens.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fMensagens.proto\"?\n\x0b\x44\x61\x64osSensor\x12\x11\n\tid_sensor\x18\x01 \x01(\t\x12\x0c\n\x04tipo\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\"=\n\x07\x43omando\x12\x0c\n\x04\x61\x63\x61o\x18\x01 \x01(\t\x12\x11\n\tid_sensor\x18\x02 \x01(\t\x12\x11\n\tparametro\x18\x03 \x01(\t\"\x1c\n\x08Resposta\x12\x10\n\x08mensagem\x18\x01 \x01(\t\"X\n\x0eRegistroSensor\x12\x11\n\tid_sensor\x18\x01 \x01(\t\x12\x0c\n\x04tipo\x18\x02 \x01(\t\x12\x0e\n\x06\x65stado\x18\x03 \x01(\t\x12\x15\n\rporta_comando\x18\x04 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Mensagens_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DADOSSENSOR']._serialized_start=19
  _globals['_DADOSSENSOR']._serialized_end=82
  _globals['_COMANDO']._serialized_start=84
  _globals['_COMANDO']._serialized_end=145
  _globals['_RESPOSTA']._serialized_start=147
  _globals['_RESPOSTA']._serialized_end=175
  _globals['_REGISTROSENSOR']._serialized_start=177
  _globals['_REGISTROSENSOR']._serialized_end=265
# @@protoc_insertion_point(module_scope)
